version: '3'
services:
    php_fpm:
        build: .docker/php-fpm
        depends_on:
            - mariadb
        volumes:
            - ./:/var/www/html/factory
            - ./var/log:/var/log
        env_file:
            - .env
        entrypoint: [ "./bin/entrypoint.sh" ]
        command: [ "php-fpm" ]
    nginx:
        build: .docker/nginx
        depends_on:
            - php_fpm
            - mariadb
        volumes:
            - ./:/var/www/html/factory
            - ./var/log:/var/log/nginx
    mariadb:
        image: mariadb:latest
        env_file:
            - .env
        volumes:
            - mariadb-factory:/var/lib/mysql
volumes:
    mariadb-factory: